require('pry-byebug')
require_relative('./sql_runner.rb')
require_relative('../models/country.rb')
require_relative('../models/competitor.rb')
require_relative('../models/event.rb')
require_relative('../models/entry.rb')
require_relative('../models/sport.rb')

#COUNTRIES
russia1 = Country.new({'name' => "Russia"})
united_states2 = Country.new({'name' => "United States"})
norway3 = Country.new({'name' => "Norway"})
australia4 = Country.new({'name' => "Australia"})
netherlands5 = Country.new({'name' => "Netherlands"})
germany6 = Country.new({'name' => "Germany"})
austria7 = Country.new({'name' => "Austria"})
france8 = Country.new({'name' => "France"})
sweden9 = Country.new({'name' => "Sweden"})
switzerland10 = Country.new({'name' => "Switzerland"})
china11 = Country.new({'name' => "China"})
korea12 = Country.new({'name' => "Korea"})

russia1.save
united_states2.save
norway3.save
australia4.save
netherlands5.save
germany6.save
austria7.save
france8.save
sweden9.save
switzerland10.save
china11.save
korea12.save

#SPORTS
sport1 = Sport.new({'name' => "Figure Skating"})
sport2 = Sport.new({'name' => "Ice Hockey"})
sport3 = Sport.new({'name' => "Luge"})
sport4 = Sport.new({'name' => "Curling"})
sport5 = Sport.new({'name' => "Freestyle Skiing"})

sport1.save()
sport2.save()
sport3.save()
sport4.save()
sport5.save()

#COMPETITORS
competitor1 = Competitor.new({'name' => "competitor1", 'country_id' => 6, 'sport_id' => 1})
competitor2 = Competitor.new({'name' => "competitor2", 'country_id' => 3, 'sport_id' => 2})
competitor3 = Competitor.new({'name' => "competitor3", 'country_id' => 8, 'sport_id' => 3})
competitor4 = Competitor.new({'name' => "competitor4", 'country_id' => 9, 'sport_id' => 4})
competitor5 = Competitor.new({'name' => "competitor5", 'country_id' => 11, 'sport_id' => 5})
competitor6 = Competitor.new({'name' => "competitor6", 'country_id' => 5, 'sport_id' => 1})
competitor7 = Competitor.new({'name' => "competitor7", 'country_id' => 1, 'sport_id' => 2})
competitor8 = Competitor.new({'name' => "competitor8", 'country_id' => 9, 'sport_id' => 3})
competitor9 = Competitor.new({'name' => "competitor9", 'country_id' => 2, 'sport_id' => 4})
competitor10 = Competitor.new({'name' => "competitor10", 'country_id' => 6, 'sport_id' => 5})
competitor11 = Competitor.new({'name' => "competitor11", 'country_id' => 7, 'sport_id' => 1})
competitor12 = Competitor.new({'name' => "competitor12", 'country_id' => 9, 'sport_id' => 2})
competitor13 = Competitor.new({'name' => "competitor13", 'country_id' => 2, 'sport_id' => 3})
competitor14 = Competitor.new({'name' => "competitor14", 'country_id' => 4, 'sport_id' => 4})
competitor15 = Competitor.new({'name' => "competitor15", 'country_id' => 10, 'sport_id' => 5})
competitor16 = Competitor.new({'name' => "competitor16", 'country_id' => 12, 'sport_id' => 1})
competitor17 = Competitor.new({'name' => "competitor17", 'country_id' => 6, 'sport_id' => 2})
competitor18 = Competitor.new({'name' => "competitor18", 'country_id' => 1, 'sport_id' => 3})
competitor19 = Competitor.new({'name' => "competitor19", 'country_id' => 3, 'sport_id' => 4})
competitor20 = Competitor.new({'name' => "competitor20", 'country_id' => 8, 'sport_id' => 5})
competitor21 = Competitor.new({'name' => "competitor21", 'country_id' => 9, 'sport_id' => 1})
competitor22 = Competitor.new({'name' => "competitor22", 'country_id' => 11, 'sport_id' => 2})
competitor23 = Competitor.new({'name' => "competitor23", 'country_id' => 10, 'sport_id' => 3})
competitor24 = Competitor.new({'name' => "competitor24", 'country_id' => 8, 'sport_id' => 4})
competitor25 = Competitor.new({'name' => "competitor25", 'country_id' => 9, 'sport_id' => 5})
competitor26 = Competitor.new({'name' => "competitor26", 'country_id' => 2, 'sport_id' => 1})
competitor27 = Competitor.new({'name' => "competitor27", 'country_id' => 8, 'sport_id' => 2})
competitor28 = Competitor.new({'name' => "competitor28", 'country_id' => 5, 'sport_id' => 3})
competitor29 = Competitor.new({'name' => "competitor29", 'country_id' => 10, 'sport_id' => 4})
competitor30 = Competitor.new({'name' => "competitor30", 'country_id' => 11, 'sport_id' => 5})
competitor31 = Competitor.new({'name' => "competitor31", 'country_id' => 6, 'sport_id' => 1})
competitor32 = Competitor.new({'name' => "competitor32", 'country_id' => 5, 'sport_id' => 2})
competitor33 = Competitor.new({'name' => "competitor33", 'country_id' => 2, 'sport_id' => 3})
competitor34 = Competitor.new({'name' => "competitor34", 'country_id' => 1, 'sport_id' => 4})
competitor35 = Competitor.new({'name' => "competitor35", 'country_id' => 9, 'sport_id' => 5})
competitor36 = Competitor.new({'name' => "competitor36", 'country_id' => 10, 'sport_id' => 1})
competitor37 = Competitor.new({'name' => "competitor37", 'country_id' => 12, 'sport_id' => 2})
competitor38 = Competitor.new({'name' => "competitor38", 'country_id' => 1, 'sport_id' => 3})
competitor39 = Competitor.new({'name' => "competitor39", 'country_id' => 8, 'sport_id' => 4})
competitor40 = Competitor.new({'name' => "competitor40", 'country_id' => 2, 'sport_id' => 5})
competitor41 = Competitor.new({'name' => "competitor41", 'country_id' => 9, 'sport_id' => 1})
competitor42 = Competitor.new({'name' => "competitor42", 'country_id' => 4, 'sport_id' => 2})
competitor43 = Competitor.new({'name' => "competitor43", 'country_id' => 6, 'sport_id' => 3})
competitor44 = Competitor.new({'name' => "competitor44", 'country_id' => 7, 'sport_id' => 4})
competitor45 = Competitor.new({'name' => "competitor45", 'country_id' => 3, 'sport_id' => 5})
competitor46 = Competitor.new({'name' => "competitor46", 'country_id' => 2, 'sport_id' => 1})
competitor47 = Competitor.new({'name' => "competitor47", 'country_id' => 8, 'sport_id' => 2})
competitor48 = Competitor.new({'name' => "competitor48", 'country_id' => 11, 'sport_id' => 3})
competitor49 = Competitor.new({'name' => "competitor49", 'country_id' => 10, 'sport_id' => 4})
competitor50 = Competitor.new({'name' => "competitor50", 'country_id' => 8, 'sport_id' => 5})
competitor51 = Competitor.new({'name' => "competitor51", 'country_id' => 4, 'sport_id' => 1})
competitor52 = Competitor.new({'name' => "competitor52", 'country_id' => 2, 'sport_id' => 2})
competitor53 = Competitor.new({'name' => "competitor53", 'country_id' => 12, 'sport_id' => 3})
competitor54 = Competitor.new({'name' => "competitor54", 'country_id' => 12, 'sport_id' => 4})
competitor55 = Competitor.new({'name' => "competitor55", 'country_id' => 5, 'sport_id' => 5})
competitor56 = Competitor.new({'name' => "competitor56", 'country_id' => 8, 'sport_id' => 1})
competitor57 = Competitor.new({'name' => "competitor57", 'country_id' => 9, 'sport_id' => 2})
competitor58 = Competitor.new({'name' => "competitor58", 'country_id' => 2, 'sport_id' => 3})
competitor59 = Competitor.new({'name' => "competitor59", 'country_id' => 4, 'sport_id' => 4})
competitor60 = Competitor.new({'name' => "competitor60", 'country_id' => 1, 'sport_id' => 5})
competitor61 = Competitor.new({'name' => "competitor61", 'country_id' => 7, 'sport_id' => 1})
competitor62 = Competitor.new({'name' => "competitor62", 'country_id' => 8, 'sport_id' => 2})
competitor63 = Competitor.new({'name' => "competitor63", 'country_id' => 4, 'sport_id' => 3})
competitor64 = Competitor.new({'name' => "competitor64", 'country_id' => 10, 'sport_id' => 4})
competitor65 = Competitor.new({'name' => "competitor65", 'country_id' => 3, 'sport_id' => 5})
competitor66 = Competitor.new({'name' => "competitor66", 'country_id' => 4, 'sport_id' => 1})
competitor67 = Competitor.new({'name' => "competitor67", 'country_id' => 8, 'sport_id' => 2})
competitor68 = Competitor.new({'name' => "competitor68", 'country_id' => 7, 'sport_id' => 3})
competitor69 = Competitor.new({'name' => "competitor69", 'country_id' => 6, 'sport_id' => 4})
competitor70 = Competitor.new({'name' => "competitor70", 'country_id' => 7, 'sport_id' => 5})
competitor71 = Competitor.new({'name' => "competitor71", 'country_id' => 8, 'sport_id' => 1})
competitor72 = Competitor.new({'name' => "competitor72", 'country_id' => 4, 'sport_id' => 2})
competitor73 = Competitor.new({'name' => "competitor73", 'country_id' => 2, 'sport_id' => 3})
competitor74 = Competitor.new({'name' => "competitor74", 'country_id' => 9, 'sport_id' => 4})
competitor75 = Competitor.new({'name' => "competitor75", 'country_id' => 1, 'sport_id' => 5})
competitor76 = Competitor.new({'name' => "competitor76", 'country_id' => 6, 'sport_id' => 1})
competitor77 = Competitor.new({'name' => "competitor77", 'country_id' => 5, 'sport_id' => 2})
competitor78 = Competitor.new({'name' => "competitor78", 'country_id' => 4, 'sport_id' => 3})
competitor79 = Competitor.new({'name' => "competitor79", 'country_id' => 4, 'sport_id' => 4})
competitor80 = Competitor.new({'name' => "competitor80", 'country_id' => 4, 'sport_id' => 5})
competitor81 = Competitor.new({'name' => "competitor81", 'country_id' => 7, 'sport_id' => 1})
competitor82 = Competitor.new({'name' => "competitor82", 'country_id' => 2, 'sport_id' => 2})
competitor83 = Competitor.new({'name' => "competitor83", 'country_id' => 2, 'sport_id' => 3})
competitor84 = Competitor.new({'name' => "competitor84", 'country_id' => 2, 'sport_id' => 4})
competitor85 = Competitor.new({'name' => "competitor85", 'country_id' => 10, 'sport_id' => 5})
competitor86 = Competitor.new({'name' => "competitor86", 'country_id' => 11, 'sport_id' => 1})
competitor87 = Competitor.new({'name' => "competitor87", 'country_id' => 11, 'sport_id' => 2})
competitor88 = Competitor.new({'name' => "competitor88", 'country_id' => 11, 'sport_id' => 3})
competitor89 = Competitor.new({'name' => "competitor89", 'country_id' => 8, 'sport_id' => 4})
competitor90 = Competitor.new({'name' => "competitor90", 'country_id' => 3, 'sport_id' => 5})
competitor91 = Competitor.new({'name' => "competitor91", 'country_id' => 5, 'sport_id' => 1})
competitor92 = Competitor.new({'name' => "competitor92", 'country_id' => 2, 'sport_id' => 2})
competitor93 = Competitor.new({'name' => "competitor93", 'country_id' => 9, 'sport_id' => 3})
competitor94 = Competitor.new({'name' => "competitor94", 'country_id' => 7, 'sport_id' => 4})
competitor95 = Competitor.new({'name' => "competitor95", 'country_id' => 7, 'sport_id' => 5})
competitor96 = Competitor.new({'name' => "competitor96", 'country_id' => 6, 'sport_id' => 1})
competitor97 = Competitor.new({'name' => "competitor97", 'country_id' => 5, 'sport_id' => 2})
competitor98 = Competitor.new({'name' => "competitor98", 'country_id' => 4, 'sport_id' => 3})
competitor99 = Competitor.new({'name' => "competitor99", 'country_id' => 5, 'sport_id' => 4})
competitor100 = Competitor.new({'name' => "competitor100", 'country_id' => 8, 'sport_id' => 5})

competitor1.save()
competitor2.save()
competitor3.save()
competitor4.save()
competitor5.save()
competitor6.save()
competitor7.save()
competitor8.save()
competitor9.save()
competitor10.save()
competitor11.save()
competitor12.save()
competitor13.save()
competitor14.save()
competitor15.save()
competitor16.save()
competitor17.save()
competitor18.save()
competitor19.save()
competitor20.save()
competitor21.save()
competitor22.save()
competitor23.save()
competitor24.save()
competitor25.save()
competitor26.save()
competitor27.save()
competitor28.save()
competitor29.save()
competitor30.save()
competitor31.save()
competitor32.save()
competitor33.save()
competitor34.save()
competitor35.save()
competitor36.save()
competitor37.save()
competitor38.save()
competitor39.save()
competitor40.save()
competitor41.save()
competitor42.save()
competitor43.save()
competitor44.save()
competitor45.save()
competitor46.save()
competitor47.save()
competitor48.save()
competitor49.save()
competitor50.save()
competitor51.save()
competitor52.save()
competitor53.save()
competitor54.save()
competitor55.save()
competitor56.save()
competitor57.save()
competitor58.save()
competitor59.save()
competitor60.save()
competitor61.save()
competitor62.save()
competitor63.save()
competitor64.save()
competitor65.save()
competitor66.save()
competitor67.save()
competitor68.save()
competitor69.save()
competitor70.save()
competitor71.save()
competitor72.save()
competitor73.save()
competitor74.save()
competitor75.save()
competitor76.save()
competitor77.save()
competitor78.save()
competitor79.save()
competitor80.save()
competitor81.save()
competitor82.save()
competitor83.save()
competitor84.save()
competitor85.save()
competitor86.save()
competitor87.save()
competitor88.save()
competitor89.save()
competitor90.save()
competitor91.save()
competitor92.save()
competitor93.save()
competitor94.save()
competitor95.save()
competitor96.save()
competitor97.save()
competitor98.save()
competitor99.save()
competitor100.save()

#EVENTS
event1 = Event.new({'name' => "Men''s Singles", 'sport_id' => 1})
event2 = Event.new({'name' => "Women''s Singles", 'sport_id' => 1})
event3 = Event.new({'name' => "Pairs", 'sport_id' => 1})
event4 = Event.new({'name' => "Ice Dance", 'sport_id' => 1})
event5 = Event.new({'name' => "Team", 'sport_id' => 1})
event6 = Event.new({'name' => "Men", 'sport_id' => 2})
event7 = Event.new({'name' => "Women", 'sport_id' => 2})
event8 = Event.new({'name' => "Men''s Singles", 'sport_id' => 3})
event9 = Event.new({'name' => "Women''s Singles", 'sport_id' => 3})
event10 = Event.new({'name' => "Doubles", 'sport_id' => 3})
event11 = Event.new({'name' => "Team Relay", 'sport_id' => 3})
event12 = Event.new({'name' => "Men", 'sport_id' => 4})
event13 = Event.new({'name' => "Women", 'sport_id' => 4})
event14 = Event.new({'name' => "Men''s Ski Slopestyle", 'sport_id' => 5})
event15 = Event.new({'name' => "Women''s Ski Slopestyle", 'sport_id' => 5})

event1.save()
event2.save()
event3.save()
event4.save()
event5.save()
event6.save()
event7.save()
event8.save()
event9.save()
event10.save()
event11.save()
event12.save()
event13.save()
event14.save()
event15.save()

#RESULTS
entry1 = Entry.new({'competitor_id' => competitor1.id, 'event_id' => event1.id, 'result' => 1})
entry2 = Entry.new({'competitor_id' => competitor21.id, 'event_id' => event1.id, 'result' => 2})
entry3 = Entry.new({'competitor_id' => competitor36.id, 'event_id' => event1.id, 'result' => 3})
entry4 = Entry.new({'competitor_id' => competitor76.id, 'event_id' => event2.id, 'result' => 1})
entry5 = Entry.new({'competitor_id' => competitor91.id, 'event_id' => event2.id, 'result' => 2})
entry6 = Entry.new({'competitor_id' => competitor66.id, 'event_id' => event2.id, 'result' => 3})
entry7 = Entry.new({'competitor_id' => competitor26.id, 'event_id' => event3.id, 'result' => 1})
entry8 = Entry.new({'competitor_id' => competitor16.id, 'event_id' => event3.id, 'result' => 2})
entry9 = Entry.new({'competitor_id' => competitor46.id, 'event_id' => event3.id, 'result' => 3})
entry10 = Entry.new({'competitor_id' => competitor1.id, 'event_id' => event4.id, 'result' => 1})
entry11 = Entry.new({'competitor_id' => competitor71.id, 'event_id' => event4.id, 'result' => 2})
entry12 = Entry.new({'competitor_id' => competitor91.id, 'event_id' => event4.id, 'result' => 3})
entry13 = Entry.new({'competitor_id' => competitor56.id, 'event_id' => event5.id, 'result' => 1})
entry14 = Entry.new({'competitor_id' => competitor86.id, 'event_id' => event5.id, 'result' => 2})
entry15 = Entry.new({'competitor_id' => competitor26.id, 'event_id' => event5.id, 'result' => 3})
entry16 = Entry.new({'competitor_id' => competitor97.id, 'event_id' => event6.id, 'result' => 1})
entry17 = Entry.new({'competitor_id' => competitor2.id, 'event_id' => event6.id, 'result' => 2})
entry18 = Entry.new({'competitor_id' => competitor32.id, 'event_id' => event6.id, 'result' => 3})
entry19 = Entry.new({'competitor_id' => competitor22.id, 'event_id' => event7.id, 'result' => 1})
entry20 = Entry.new({'competitor_id' => competitor67.id, 'event_id' => event7.id, 'result' => 2})
entry21 = Entry.new({'competitor_id' => competitor67.id, 'event_id' => event7.id, 'result' => 3})
entry22 = Entry.new({'competitor_id' => competitor73.id, 'event_id' => event8.id, 'result' => 1})
entry23 = Entry.new({'competitor_id' => competitor68.id, 'event_id' => event8.id, 'result' => 2})
entry24 = Entry.new({'competitor_id' => competitor23.id, 'event_id' => event8.id, 'result' => 3})
entry25 = Entry.new({'competitor_id' => competitor48.id, 'event_id' => event9.id, 'result' => 1})
entry26 = Entry.new({'competitor_id' => competitor68.id, 'event_id' => event9.id, 'result' => 2})
entry27 = Entry.new({'competitor_id' => competitor33.id, 'event_id' => event9.id, 'result' => 3})
entry28 = Entry.new({'competitor_id' => competitor73.id, 'event_id' => event10.id, 'result' => 1})
entry29 = Entry.new({'competitor_id' => competitor28.id, 'event_id' => event10.id, 'result' => 2})
entry30 = Entry.new({'competitor_id' => competitor18.id, 'event_id' => event10.id, 'result' => 3})
entry31 = Entry.new({'competitor_id' => competitor43.id, 'event_id' => event11.id, 'result' => 1})
entry32 = Entry.new({'competitor_id' => competitor88.id, 'event_id' => event11.id, 'result' => 2})
entry33 = Entry.new({'competitor_id' => competitor63.id, 'event_id' => event11.id, 'result' => 3})
entry34 = Entry.new({'competitor_id' => competitor24.id, 'event_id' => event12.id, 'result' => 1})
entry35 = Entry.new({'competitor_id' => competitor59.id, 'event_id' => event12.id, 'result' => 2})
entry36 = Entry.new({'competitor_id' => competitor44.id, 'event_id' => event12.id, 'result' => 3})
entry37 = Entry.new({'competitor_id' => competitor29.id, 'event_id' => event13.id, 'result' => 1})
entry38 = Entry.new({'competitor_id' => competitor49.id, 'event_id' => event13.id, 'result' => 2})
entry39 = Entry.new({'competitor_id' => competitor89.id, 'event_id' => event13.id, 'result' => 3})
entry40 = Entry.new({'competitor_id' => competitor75.id, 'event_id' => event14.id, 'result' => 1})
entry41 = Entry.new({'competitor_id' => competitor30.id, 'event_id' => event14.id, 'result' => 2})
entry42 = Entry.new({'competitor_id' => competitor50.id, 'event_id' => event14.id, 'result' => 3})
entry43 = Entry.new({'competitor_id' => competitor55.id, 'event_id' => event15.id, 'result' => 1})
entry44 = Entry.new({'competitor_id' => competitor95.id, 'event_id' => event15.id, 'result' => 2})
entry45 = Entry.new({'competitor_id' => competitor45.id, 'event_id' => event15.id, 'result' => 3})

entry1.save()
entry2.save()
entry3.save()
entry4.save()
entry5.save()
entry6.save()
entry7.save()
entry8.save()
entry9.save()
entry10.save()
entry11.save()
entry12.save()
entry13.save()
entry14.save()
entry15.save()
entry16.save()
entry17.save()
entry18.save()
entry19.save()
entry20.save()
entry21.save()
entry22.save()
entry23.save()
entry24.save()
entry25.save()
entry26.save()
entry27.save()
entry28.save()
entry29.save()
entry30.save()
entry31.save()
entry32.save()
entry33.save()
entry34.save()
entry35.save()
entry36.save()
entry37.save()
entry38.save()
entry39.save()
entry40.save()
entry41.save()
entry42.save()
entry43.save()
entry44.save()
entry45.save()

# germany6.competitors
# competitor.bronze_medallists
# Country.rank_all
# event1.gold_medallist


# binding.pry
# nil